### PR TITLE
[MRG] Add better installation

### PR DESCRIPTION
**Pull request by swagshaw**
support pip installation: `pip install migperf `
package is available on https://pypi.org/project/migperf/

### CODE REVIEW

**Comment by swagshaw** [comment]
#25

**Comment by dixing0908** [comment]
I tried `pip install MIG-Profiler` and followed instruction in readme and failed. Here is the result:
image

**Comment by swagshaw** [comment]
@dixing0908 

Please make sure all required packages are inside the 'requirements.txt'.

image
image

The requirements.txt doesn't include the torch and others now. Please fix it.
I will generate it again after you fix the requirements.txt.

**Comment by dixing0908** [comment]
> datasets==2.4.0
> opencv-python
> prometheus-client==0.15.0
> sanic==22.9.1
> tqdm==4.64.1
> transformers==4.25.1
> opencv-contrib-python
> --find-links https://download.pytorch.org/whl/torch_stable.html
> torch==1.13.0+cu116
> torchvision==0.14.0+cu116
> numpy==1.23.4
Try this requirements, and update the requirements.txt as this one.

**Pull request merged**
